Create spanish translations
fuckur-mom/home pull request #6
Opened 2022-05-16 13:57 UTC by bilibilixkz

2022-05-16 15:12 UTC, AH-dark requested changes

2022-05-16 15:12 UTC, AH-dark commented on src/lang/index.ts
> +    "es-MX": "Español (México)";
为什么是墨西哥版？

2022-05-16 15:12 UTC, AH-dark commented on src/lang/translation/es_MX.ts
> +﻿import TranslationModel from "./model";const esMX: TranslationModel = {    HomeContext: {        "Fuck Your Mom": "Fuck Your Mom",        "There is a homepage that explains what the project doe
您缩进呢？？？

2022-05-17 01:41 UTC, bilibilixkz commented on src/lang/translation/es_MX.ts
> +﻿import TranslationModel from "./model";const esMX: TranslationModel = {    HomeContext: {        "Fuck Your Mom": "Fuck Your Mom",        "There is a homepage that explains what the project doe
淦，换行符用错了

2022-05-17 01:58 UTC, AH-dark requested changes

2022-05-17 01:58 UTC, AH-dark commented on src/lang/index.ts
> +    "es-MX": "Español (México)";
请使用 `;` 结尾...

2022-05-17 02:49 UTC, bilibilixkz commented on src/lang/index.ts
> +    "es-MX": "Español (México)";
已修改

2022-05-17 03:12 UTC, AH-dark requested changes

2022-05-17 03:12 UTC, AH-dark commented on src/lang/index.ts
> +    "es-MX": "Español (México)";,
我不理解，你把分号去掉啊！

2022-05-17 04:45 UTC, bilibilixkz commented on src/lang/index.ts
> +    "es-MX": "Español (México)";,
已修改

2022-05-17 04:46 UTC, AH-dark approved these changes

2022-05-17 04:47 UTC, merged